# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'SirBart2.xcodeproj'

target 'SirBart2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#  target 'SirBart2Tests' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
    inherit! :search_paths
    # Pods for testing
#  platform :ios, '9.0'
#  end

end

