# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SirBart2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SirBart2
  pod 'Firebase/Core'

  target 'SirBart2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

