/* @flow */
export const stationNames = {
  "12TH": "12th St Oakland City Center",
  "16TH": "16th St Mission",
  "19TH": "19th St Oakland",
  "24TH": "24th St Mission",
  ASHB: "Ashby",
  BALB: "Balboa Park",
  BAYF: "Bay Fair",
  CAST: "Castro Valley",
  CIVC: "Civic Center UN Plaza",
  COLS: "Coliseum Oakland Airport",
  COLM: "Colma",
  CONC: "Concord",
  DALY: "Daly City",
  DBRK: "Downtown Berkeley",
  DUBL: "Dublin Pleasanton",
  DELN: "El Cerrito del Norte",
  PLZA: "El Cerrito Plaza",
  EMBR: "Embarcadero",
  FRMT: "Fremont",
  FTVL: "Fruitvale",
  GLEN: "Glen Park",
  HAYW: "Hayward",
  LAFY: "Lafayette",
  LAKE: "Lake Merritt",
  MCAR: "MacArthur",
  MLBR: "Millbrae",
  MONT: "Montgomery St",
  NBRK: "North Berkeley",
  NCON: "North Concord Martinez",
  OAKL: "Oakland Intl Airport",
  ORIN: "Orinda",
  PITT: "Pittsburg Bay Point",
  PHIL: "Pleasant Hill",
  POWL: "Powell St",
  RICH: "Richmond",
  ROCK: "Rockridge",
  SBRN: "San Bruno",
  SFIA: "San Francisco Intl Airport",
  SANL: "San Leandro",
  SHAY: "South Hayward",
  SSAN: "South San Francisco",
  UCTY: "Union City",
  WCRK: "Walnut Creek",
  WDUB: "West Dublin",
  WOAK: "West Oakland",
};
